/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a fguControlAdaptor -i fguControlCommon.h -c FguControlAdaptor cz.cas.fgu.control.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "fguControlAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class FguControlAdaptor
 */

FguControlAdaptor::FguControlAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

FguControlAdaptor::~FguControlAdaptor()
{
    // destructor
}

FguControlVideoSettings FguControlAdaptor::get_video_settings()
{
    // handle method call cz.cas.fgu.control.get_video_settings
    FguControlVideoSettings settings;
    QMetaObject::invokeMethod(parent(), "get_video_settings", Q_RETURN_ARG(FguControlVideoSettings, settings));
    return settings;
}

FguControlVideoSettings FguControlAdaptor::set_video_settings(int vres, int hres, double framerate)
{
    // handle method call cz.cas.fgu.control.set_video_settings
    FguControlVideoSettings settings;
    QMetaObject::invokeMethod(parent(), "set_video_settings", Q_RETURN_ARG(FguControlVideoSettings, settings), Q_ARG(int, vres), Q_ARG(int, hres), Q_ARG(double, framerate));
    return settings;
}

